version: '3.3'
services:
    gm-app:
        extends:
            file: docker-compose-base.yml
            service: gm-app
        volumes:
            - type: bind
              source: ../
              target: /CODE
        command: >
            bash -c "npm i && npm run start-dev"

    gm-app-postgres:
        extends:
            file: docker-compose-base.yml
            service: gm-app-postgres

    # mongo:
    #     extends:
    #         file: docker-compose-base.yml
    #         service: mongo

volumes:
    # application_mongo_db:
    gm-app-postgres-db:
# application_files:

networks:
    gm-app-network:
