version: '3.3'
services:
    application:
        extends:
            file: docker-compose-base.yml
            service: application
        volumes:
            - type: bind
              source: ../
              target: /CODE
        command: >
            bash -c "npm i && npm run start-dev"

    # postgres:
    #     extends:
    #         file: docker-compose-base.yml
    #         service: postgres

    # mongo:
    #     extends:
    #         file: docker-compose-base.yml
    #         service: mongo

# volumes:
    # application_mongo_db:
    # application_postgresql_db:
    # application_files:

networks:
    application_network:
