version: '3.3'

services:
    gm-app:
        container_name: gm-app
        image: node:18.12.1
        stdin_open: true
        tty: true
        working_dir: /CODE
        env_file:
            - ../.env
        restart: unless-stopped
        networks:
            - gm-app-network

    gm-app-postgres:
        container_name: gm-app-postgres
        image: postgres
        restart: unless-stopped
        ports:
            - '5433:5432'
        env_file:
            - ../.env
        volumes:
            - gm-app-postgres-db:/var/lib/postgresql/data
        networks:
            - gm-app-network

    # mongo:
    #     container_name: db_mongo
    #     image: mongo
    #     restart: unless-stopped
    #     ports:
    #         - '27017:27017'
    #     env_file:
    #         - ../.env
    #     volumes:
    #         - application_mongo_db:/data/db
    #     networks:
    #         - application_network

volumes:
    # application_mongo_db:
    gm-app-postgres-db:
# application_files:

networks:
    gm-app-network:
